<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Subdomenii</title>
</head>
<body>
  <h1>Subdomenii:</h1>
  <ul>
    <li><a href="https://akuma9923.github.io/metamask-recovery.com/subdomeniu1/">Subdomeniu1</a></li>
    <li><a href="https://akuma9923.github.io/metamask-recovery.com/subdomeniu2/">Subdomeniu2</a></li>
    <!-- Adaugă oricâte subdomenii dorești -->
  </ul>
</body>
</html>
title: Metamask Recovery
Recover Your Metamask Account
description: Descrierea Site-ului
theme: minima # Sau poți folosi un alt tema
plugins:
  - jekyll-feed
