name: Static Site Deploy

on:
  push:
    branches:
      - main  # Actualizează cu numele branch-ului tău principal

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        publish_dir: ./  # Actualizează cu directorul în care se află fișierele statice ale site-ului tău
        force_orphan: true
